#!/usr/bin/env tsx
/**
 * Seed test users in prod Clerk + prod Supabase for E2E + on-demand browser testing.
 *
 * Idempotent — safe to re-run. Existing test users have their passwords rotated.
 *
 * Inputs: .env.seed.local at repo root
 *   CLERK_SECRET_KEY=...
 *   SUPABASE_URL=...
 *   SUPABASE_SERVICE_KEY=...
 *
 * Outputs: .env.test.local at repo root
 *   TEST_USER_EMAIL=eggs-test-pro@aulson.pro
 *   TEST_USER_PASSWORD=<generated>
 *   FREE_TEST_USER_EMAIL=eggs-test-free@aulson.pro
 *   FREE_TEST_USER_PASSWORD=<generated>
 *
 * Usage (from repo root or eggs-api/):
 *   npm run seed-test-users
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { randomBytes } from 'node:crypto'
import { config as dotenvConfig } from 'dotenv'
import { createClerkClient } from '@clerk/backend'
import { createClient } from '@supabase/supabase-js'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const REPO_ROOT = resolve(__dirname, '../..')
const SEED_ENV_PATH = resolve(REPO_ROOT, '.env.seed.local')
const TEST_ENV_PATH = resolve(REPO_ROOT, '.env.test.local')

if (!existsSync(SEED_ENV_PATH)) {
  console.error(`✖ Missing ${SEED_ENV_PATH}`)
  console.error('  Create it with:')
  console.error('    CLERK_SECRET_KEY=sk_live_...')
  console.error('    SUPABASE_URL=https://<project>.supabase.co')
  console.error('    SUPABASE_SERVICE_KEY=...')
  process.exit(1)
}

dotenvConfig({ path: SEED_ENV_PATH })

const CLERK_SECRET_KEY = process.env.CLERK_SECRET_KEY
const SUPABASE_URL = process.env.SUPABASE_URL
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_KEY

for (const [k, v] of [
  ['CLERK_SECRET_KEY', CLERK_SECRET_KEY],
  ['SUPABASE_URL', SUPABASE_URL],
  ['SUPABASE_SERVICE_KEY', SUPABASE_SERVICE_KEY]
] as const) {
  if (!v) {
    console.error(`✖ Missing ${k} in .env.seed.local`)
    process.exit(1)
  }
}

interface Account {
  email: string
  tier: 'free' | 'pro'
  envPrefix: 'TEST_USER' | 'FREE_TEST_USER'
  displayName: string
}

const ACCOUNTS: Account[] = [
  {
    email: 'eggs-test-free@aulson.pro',
    tier: 'free',
    envPrefix: 'FREE_TEST_USER',
    displayName: 'Free Test User'
  },
  {
    email: 'eggs-test-pro@aulson.pro',
    tier: 'pro',
    envPrefix: 'TEST_USER',
    displayName: 'Pro Test User'
  }
]

function randomPassword(): string {
  // 24 random bytes → 32-char base64url; Clerk requires >= 8 chars and not a
  // common/breached password. Random strings pass its HIBP check reliably.
  return randomBytes(24).toString('base64url')
}

const clerk = createClerkClient({ secretKey: CLERK_SECRET_KEY! })
const supabase = createClient(SUPABASE_URL!, SUPABASE_SERVICE_KEY!, {
  auth: { persistSession: false }
})

interface SeededAccount extends Account {
  userId: string
  password: string
}

async function seedOne(acct: Account): Promise<SeededAccount> {
  const password = randomPassword()

  // Find existing Clerk user by email
  const existing = await clerk.users.getUserList({ emailAddress: [acct.email] })

  let userId: string
  if (existing.data.length > 0) {
    userId = existing.data[0].id
    console.log(`[clerk] ${acct.email} — exists (id=${userId}), rotating password + metadata`)
    await clerk.users.updateUser(userId, {
      password,
      publicMetadata: { is_test_account: true, tier: acct.tier }
    })
  } else {
    console.log(`[clerk] ${acct.email} — creating`)
    const user = await clerk.users.createUser({
      emailAddress: [acct.email],
      password,
      publicMetadata: { is_test_account: true, tier: acct.tier }
    })
    userId = user.id
  }

  // Upsert Supabase row
  const { error } = await supabase
    .from('users')
    .upsert(
      {
        id: userId,
        email: acct.email,
        display_name: acct.displayName,
        subscription_tier: acct.tier,
        subscription_status: acct.tier === 'pro' ? 'active' : 'active',
        is_test_account: true,
        default_location_lat: 32.7767,
        default_location_lng: -96.7970,
        default_location_label: 'Dallas, TX 75201'
      },
      { onConflict: 'id', ignoreDuplicates: false }
    )

  if (error) {
    console.error(`[supabase] upsert failed for ${acct.email}: ${error.message}`)
    throw error
  }
  console.log(`[supabase] ${acct.email} — upserted as ${acct.tier}`)

  return { ...acct, userId, password }
}

async function main() {
  console.log('Seeding test users...\n')
  const seeded: SeededAccount[] = []
  for (const acct of ACCOUNTS) {
    seeded.push(await seedOne(acct))
  }

  // Write .env.test.local
  const lines = [
    '# Generated by seed-test-users.ts',
    `# ${new Date().toISOString()}`,
    '# Gitignored — never commit.',
    ''
  ]
  for (const s of seeded) {
    lines.push(`${s.envPrefix}_EMAIL=${s.email}`)
    lines.push(`${s.envPrefix}_PASSWORD=${s.password}`)
    lines.push(`${s.envPrefix}_CLERK_ID=${s.userId}`)
    lines.push('')
  }
  writeFileSync(TEST_ENV_PATH, lines.join('\n'))
  console.log(`\n✓ Wrote ${TEST_ENV_PATH}`)

  console.log('\nGitHub Actions secrets to set (values in .env.test.local):')
  for (const s of seeded) {
    console.log(`  ${s.envPrefix}_EMAIL`)
    console.log(`  ${s.envPrefix}_PASSWORD`)
    console.log(`  ${s.envPrefix}_CLERK_ID`)
  }

  console.log('\nDone. You can now:')
  console.log(`  rm ${SEED_ENV_PATH}   # (optional) scrub the seed secrets from disk`)
  console.log('  npm run test:e2e:smoke  # run Playwright E2E using the seeded accounts')
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
